data = {
    #data of normal pea bullet
    0 : {
        'PATH' : 'picture/Bullet/PeaBullet/0.png',
        'SUMMON_SOUND_PATH' : 'sound/bulletExplode.ogg',
        'IMAGE_INDEX_MAX' : 0,
        'IMAGE_INDEX_CD' : 0.00,
        'POSITION_CD' : 0.01,
        'SIZE' : (56, 34),
        'COLLIDE_DEVIATION' : 20,
        'COLLIDE_DEVIATION_Y' : 0,
        'COLLIDE_SIZE' : (30, 34),
        'SPEED' : (5, 0),
        'SUMMON_CD' : -1,
        'CANPICK' : False,
        'CANFIGHT' : True,
        'PRICE' : 0,
        'HP' : 1,
        'ATK' : 20,
    },

    #data of normal zombie
    1 : {
        'PATH' : 'picture/Zombie/NormalZombie/%d.png',
        'IMAGE_INDEX_MAX' : 22,
        'IMAGE_INDEX_CD' : 0.1,
        'POSITION_CD' : 0.01,
        'SIZE' : (166, 144),
        'COLLIDE_DEVIATION' : 85,
        'COLLIDE_DEVIATION_Y' : 50,
        'COLLIDE_SIZE' : (20, 70),
        'SPEED' : (-0.9, 0),
        'SUMMON_CD' : -1,
        'ATTACK_CD' : 0.5,
        'CANPICK' : False,
        'CANFIGHT' : True,
        'PRICE' : 0,
        'HP' : 200,
        'ATK' : 10,
    },

    #data of sunshine
    2 : {
            'PATH' : 'picture/Sunshine/%d.png',
            'SOUND_PATH' : 'sound/collectSun.ogg',
            'IMAGE_INDEX_MAX' : 22,
            'IMAGE_INDEX_CD' : 0.04,
            'POSITION_CD' : 0.05,
            'SIZE' : (78, 78),
            'COLLIDE_DEVIATION' : 0,
            'COLLIDE_DEVIATION_Y' : 0,
            'COLLIDE_SIZE' : (78, 78),
            'SPEED' : (0, 1),
            'SUMMON_CD' : -1,
            'CANPICK' : True,
            'CANFIGHT' : False,
            'PRICE' : 25,
            'HP' : 200000,
            'ATK' : 0,
        },

    #data of sun flower
    3 : {
            'PATH' : 'picture/Plant/sunFlower/%d.png',
            'IMAGE_INDEX_MAX' : 18,
            'IMAGE_INDEX_CD' : 0.1,
            'POSITION_CD' : 100000,
            'SIZE' : (73, 74),
            'COLLIDE_DEVIATION' : 0,
            'COLLIDE_DEVIATION_Y' : 0,
            'COLLIDE_SIZE' : (73, 50),
            'SPEED' : (0, 0),
            'SUMMON_CD' : 8,
            'CANPICK' : False,
            'CANFIGHT' : True,
            'PRICE' : 50,
            'HP' : 100,
            'ATK' : 0,
        },

    #data of pea shooter
    4 : {
            'PATH' : 'picture/Plant/peaShooter/%d.png',
            'IMAGE_INDEX_MAX' : 5,
            'IMAGE_INDEX_CD' : 0.2,
            'POSITION_CD' : 100000,
            'SIZE' : (71, 71),
            'COLLIDE_DEVIATION' : 0,
            'COLLIDE_DEVIATION_Y' : 0,
            'COLLIDE_SIZE' : (71, 50),
            'SPEED' : (0, 0),
            'SUMMON_CD' : 1,
            'CANPICK' : False,
            'CANFIGHT' : True,
            'PRICE' : 100,
            'HP' : 100,
            'ATK' : 0,
        },
}